import { contextBridge, ipcRenderer } from 'electron'

function subscribe(channel: string, listener: (...args: any[]) => void) {
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

contextBridge.exposeInMainWorld('api', {
  storeGet: (key: string) => ipcRenderer.invoke('store:get', key),
  storeSet: (key: string, val: any) => ipcRenderer.invoke('store:set', key, val),
  storeGetAll: () => ipcRenderer.invoke('store:getAll'),
  tabsContextMenu: (id: string) => ipcRenderer.invoke('tabs:contextMenu', id),
  onSiteFocused: (cb: () => void) => subscribe('site:focused', () => cb()),
  onTabMenuAction: (cb: (id: string, action: string) => void) => subscribe('tabs:menuAction', (_e, id, action) => cb(id, action)),
  tabsCreate: (url: string) => ipcRenderer.invoke('tabs:create', url),
  tabsClose: (id: string) => ipcRenderer.invoke('tabs:close', id),
  tabsReorder: (order: string[]) => ipcRenderer.invoke('tabs:reorder', order),
  tabsTogglePinned: (id: string) => ipcRenderer.invoke('tabs:togglePinned', id),
  tabsToggleMuted: (id: string) => ipcRenderer.invoke('tabs:toggleMuted', id),
  siteSetBaseUrl: (url: string) => ipcRenderer.invoke('site:setBaseUrl', url),
  tabsSwitch: (id: string) => ipcRenderer.invoke('tabs:switch', id),
  tabsNavigate: (id: string, url: string) => ipcRenderer.invoke('tabs:navigate', id, url),
  tabsReloadActive: () => ipcRenderer.invoke('tabs:reloadActive'),
  viewSet: (mode: string) => ipcRenderer.invoke('view:set', mode),
  sidebarSetCollapsed: (v: boolean) => ipcRenderer.invoke('sidebar:setCollapsed', v),
  appVersion: () => ipcRenderer.invoke('app:version'),
  appToggleDevTools: () => ipcRenderer.invoke('app:toggleDevTools'),
  appCheckUpdate: () => ipcRenderer.invoke('app:checkUpdate'),
  appOpenUrl: (url: string) => ipcRenderer.invoke('app:openUrl', url),
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: () => ipcRenderer.invoke('accounts:add'),
  accountsSelect: (id: string) => ipcRenderer.invoke('accounts:select', id),
  accountsSetNickname: (id: string, nickname: string) => ipcRenderer.invoke('accounts:setNickname', id, nickname),
  accountsRemove: (id: string) => ipcRenderer.invoke('accounts:remove', id),
  achievementsFetch: () => ipcRenderer.invoke('achievements:fetch'),
  utilitiesList: () => ipcRenderer.invoke('utilities:list'),
  utilitiesToggle: (id: 'xp-checker') => ipcRenderer.invoke('utilities:toggle', id),
  authState: () => ipcRenderer.invoke('auth:state'),
  onAuthUpdated: (cb: (s: any) => void) => subscribe('auth:updated', (_e, s) => cb(s)),
  anomalyState: () => ipcRenderer.invoke('anomaly:state'),
  detectorToggle: (enabled?: boolean) => ipcRenderer.invoke('detector:toggle', enabled),
  detectorSound: () => ipcRenderer.invoke('detector:sound'),
  detectorToast: () => ipcRenderer.invoke('detector:toast'),
  followbackToggle: () => ipcRenderer.invoke('followback:toggle'),
  followbackState: () => ipcRenderer.invoke('followback:state'),
  followbackWhitelist: (names: string[], profile: string) => ipcRenderer.invoke('followback:whitelist', names, profile),
  followbackBlacklist: (names: string[], profile: string) => ipcRenderer.invoke('followback:blacklist', names, profile),
  detectorCollect: () => ipcRenderer.invoke('detector:collect'),
  onFollowbackState: (cb: () => void) => subscribe('followback:stateChanged', () => cb()),
  onJournalClear: (cb: () => void) => subscribe('journal:clear', () => cb()),
  onDetectorUpdated: (cb: (d: any) => void) => subscribe('detector:updated', (_e, d) => cb(d)),
  onUtilitiesUpdated: (cb: (items: any[]) => void) => subscribe('utilities:updated', (_e, items) => cb(Array.isArray(items) ? items : [])),
  onAnomalyDetected: (cb: (info: any) => void) => subscribe('anomaly:detected', (_e, info) => cb(info || {})),
  onAnomalyCollected: (cb: (info: any) => void) => subscribe('anomaly:collect-result', (_e, info) => cb(info || {})),
  googleLogin: () => ipcRenderer.invoke('google:login'),
  onTabsUpdated: (cb: (tabs: any, activeTabId: string | null) => void) => subscribe('tabs:updated', (_e, tabs, activeTabId) => cb(tabs, activeTabId)),
  onSiteNavigationBlocked: (cb: () => void) => subscribe('site:navigationBlocked', () => cb()),
  onAccountsUpdated: (cb: (accounts: any[], activeId: string) => void) => subscribe('accounts:updated', (_e, accounts, activeId) => cb(accounts, activeId)),
  onTabsLimit: (cb: () => void) => subscribe('tabs:limit', () => cb()),
  onFollowbackDone: (cb: (names: string[]) => void) => subscribe('followback:done', (_e, names) => cb(Array.isArray(names) ? names : [])),
  onFollowbackTick: (cb: (ts: number, summary: any) => void) => subscribe('followback:tick', (_e, ts, summary) => cb(Number(ts) || 0, summary || null)),
  followbackReset: () => ipcRenderer.invoke('followback:reset'),
  winMinimize: () => ipcRenderer.send('win:minimize'),
  winMaximize: () => ipcRenderer.send('win:maximize'),
  winClose: () => ipcRenderer.send('win:close')
})
